"""Added created_at to product table

Revision ID: 33c7f115bdab
Revises: e0c0373a3872
Create Date: 2025-07-22 13:50:27.924122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c7f115bdab'
down_revision: Union[str, Sequence[str], None] = 'e0c0373a3872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###
